name: 'Generic Releasr'
description: 'Github Action that allows you to commit local changes & tag Generic repositories'
inputs:
  version_metadata_path:
    description: 'Path to file containing Version string'
    required: true
    default: 'VERSION'
  author_name:
    description: 'Commit Author'
    required: true
    default: 'packagrio-bot'
  author_email:
    description: 'Commit Author Email'
    required: true
    default: 'packagr-io[bot]@users.noreply.github.com'
  cwd:
    description: 'Working Directory'
    required: false
    default: ''
  generic_version_template:
    description: 'Template used for updating metadata file'
    required: true
    default: 'version := "%d.%d.%d"'
  generic_merge_version_file:
    description: "Don't overwrite the entire version file, but merge using the template pattern"
    type: boolean
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PACKAGR_VERSION_METADATA_PATH: ${{ inputs.version_metadata_path }}
    PACKAGR_GENERIC_VERSION_TEMPLATE: ${{ inputs.generic_version_template }}
    PACKAGR_ENGINE_GIT_AUTHOR_NAME: ${{ inputs.author_name }}
    PACKAGR_ENGINE_GIT_AUTHOR_EMAIL: ${{ inputs.author_email }}
    CUSTOM_WORKING_DIRECTORY: ${{ inputs.cwd }}
    PACKAGR_GENERIC_MERGE_VERSION_FILE: ${{ inputs.generic_merge_version_file }}
branding:
  icon: 'tag'
  color: 'blue'
